### PR TITLE
README.md: Add link to Helm-SLY.

### LINKED ISSUE #267: Mention Helm-SLY in the readme?
Now that Helm-SLY is up, what about mentioning it in the README, maybe after the contribs?

### PR DESCRIPTION
**Pull request by Ambrevar**
Fix #267 .

### CODE REVIEW

**Comment by Ambrevar** [comment]
Friendly ping! :)
Anything blocking this merge?  I've used Helm-SLY for a year now, it works pretty well!

**Comment by joaotavora** [comment]
I'm hesitant to do this.  Last time, I checked Helm support for SLY's uses of Emacs completion framework was missing a bit.  I posted a simple workaround somewhere.  I don't know if "Helm-SLY" _is_ that workaround.

**Comment by Ambrevar** [comment]
I know, I was part of the discussion ;)

It all works except for the non-company-based completion.  Helm-SLY
completion works when company-mode is on.

**Comment by joaotavora** [comment]
Can you point me to that discussion again?  I'm fairly sure the workaround I came up with was satisfactory for all company and non-company use cases (though I may be wrong).

**Comment by Ambrevar** [comment]
I think you mean this: https://github.com/emacs-helm/helm-sly/issues/2

So you suggest patching helm-get-candidates?

I could add an advice in Helm-SLY.
I'll test it.

**Comment by joaotavora** [comment]
Actually, I think I meant this:

https://github.com/joaotavora/sly/issues/303#issuecomment-694112449

Which contains an advice purely for `helm-comp-read-get-candidates`.  I'd love for you to test it.  Maybe your `helm-sly`  isn't needed at all, that'd be great right.  Anyway, closing this as we can continue in #303.

**Comment by Ambrevar** [comment]
Seems to work for me!

Can you explain the (inhibit-quit t) patch?
The `inhibit-quit` docstring says:

> Non-nil inhibits C-g quitting from happening immediately.
> 
> Note that quit-flag will still be set by typing C-g,
> so a quit will be signaled as soon as inhibit-quit is nil.
> To prevent this happening, set quit-flag to nil
> before making inhibit-quit nil.

I don't understand how this is related to `completion-at-point-functions'.

**Comment by joaotavora** [comment]
> Can you explain the (inhibit-quit t) patch?

No. :-)  Indeed, the whole of #303 is trying to discover why Helm is so sensitive to this.  It messes a lot with these variables, and this fix was empirically found to DTRT. (Apparently, please give it as much testing as you can).

**Comment by Ambrevar** [comment]
If you closed this, does it mean you are not willing to add a Helm SLY
mention to the readme?

**Comment by joaotavora** [comment]
I'm more concerned with making SLY work with Helm without the need for any extra packages. In principle, the way SLY hooks onto Emacs API for completion should ensure that, as long as Helm does the same.  It works for most other completion frameworks, except for Ivy (until it starts adhering to `completion-styles`) and Helm (very close except for this outstanding quirk that no-one quite understands). 

In general, I don't like these "glue packages" between A and B, because they take the focus away from what should be the real glue, which is Emacs's API. Packages should just adhere to _that_.  If that proves to be insufficient, then Emacs's API should be augmented or fixed (in this particular case though, I don't think it is).

**Comment by Ambrevar** [comment]
I fully agree with you, but:

- Some of these changes are not going to see the light anytime soon, so
in the meantime I prefer to offer a local workaround.  After all,
Helm-SLY is short and easy to maintain.

- Helm-SLY is not just about completion (I was under the impression that
you misunderstood this in the discussion).  Helm-SLY also adds Apropos
completion, helm-sly-mini (a collection of SLY buffers), and Xref
completion.

About Xref, it'd be nice to add completion in SLY.

**Comment by joaotavora** [comment]
> - Some of these changes are not going to see the light anytime soon, so in the meantime I prefer to offer a local workaround. After all, Helm-SLY is short and easy to maintain.

What changes?

> - Helm-SLY is not just about completion (I was under the impression that you misunderstood this in the discussion).  Helm-SLY also adds Apropos completion, helm-sly-mini (a collection of SLY buffers), and Xref completion.

Apropos completion is a bit odd (it's supposed to match symbol names against a pattern), but I guess you could propose adding it to SLY. `helm-sly-mini` I have no idea what is, but likewise.  And likewise for Xref completion.

> About Xref, it'd be nice to add completion in SLY.

Exactly. Ideally, I'd like you to work on integrating these things in SLY, and/or Emacs, so they can be enjoyed by others, not just Helm users. 

Of course, integration is hard, takes thought and discussion. I see you're enthusiastic about SLY, and I don't want to waste that valuable energy, so I guess I guess a mention to Helm-SLY could be added to the README.  But first, I'd add a sly-specific advice-based workaround for the `inhibit-quit` problem to `sly.el` and I'd preface the link by stating that SLY works with Helm out of the box, and Helm-SLY adds some bells and whistles.

**Comment by Ambrevar** [comment]
> What changes?

I meant the upstream Emacs changes with regard to completion.  Emacs
development is rather slow and conservative, so I guess it will take a
while before we get a more powerful completion framework in Emacs :p

> Apropos completion is a bit odd (it's supposed to match symbol names
> against a pattern), but I guess you could propose adding it to SLY.

Maybe a recipe would clarify what this means (I could also make a Gif! :p):

- If I start typing "for", then Helm displays

  CFFI:ADJUST-FOR-ALIGNMENT
  CFFI:CHECK-FOR-TYPEDEF-CYCLES
  ...

- Then I type "m" (after the "for"), _still in the same minibuffer_.
  Now the candidate list is updated to

  FARE-UTILS:TEST-FORM  
  CFFI-GROVEL:FORM-KIND
  ...

The point of live-narrowing completion is that you skip the "command ->
input -> result -> command ..." cycle.  No need to recall the search
command over and over, it's all just one thing which makes the users
life much easier.


> `helm-sly-mini` I have no idea what is, but likewise.

Completion over the list of Lisp buffers, SLY buffers, REPLs /
connections, etc.
All in one, with contextual actions like "Set default" for connections.

"Actions" are Helm-specific, sadly I don't think it's doable with other
completion framework.

> And likewise for Xref completion.
>
>> About Xref, it'd be nice to add completion in SLY.
>
> Exactly. Ideally, I'd like you to work on integrating these things in SLY, and/or Emacs, so they can be enjoyed by others, not just Helm users. 
>
> Of course, integration is hard, takes thought and discussion. I see you're enthusiastic about SLY, and I don't want to waste that valuable energy, so I guess I guess a mention to Helm-SLY could be added to the README.  But first, I'd add a sly-specific advice-based workaround for the `inhibit-quit` problem to `sly.el` and I'd preface the link by stating that SLY works with Helm out of the box, and Helm-SLY adds some bells and whistles.

I wholeheartedly agree, and sure thing I'd be happy to contribute some
of these features.

To dispel a myth around Helm that Helm users want so
badly to implement features within their own circle, I do contribute to
upstream systematically when I can ;)

No, the problem is rather that many of these features are Helm-specific,
like the `helm-sly-mini` thing.

I suggested adding Xref completion to SLY because it's the only one that
does _not_ have the following Helm-specific features:

- Multi-source (helm-sly-apropos lists symbols from current package, all
  packages, etc.)

- Actions (like the "set default" in Helm-sly-mini).

With all that said, some completion improvement can be added to
sly-apropos, I'll see if I can come up with a suggestion.

**Comment by joaotavora** [comment]
Pierre Neidhardt <notifications@github.com> writes:

>> What changes?
>
> I meant the upstream Emacs changes with regard to completion. Emacs
> development is rather slow and conservative, so I guess it will take a
> while before we get a more powerful completion framework in Emacs :p

Well, if no-one takes up the job, and hacks on their own thing, then it
never gets done.  Emacs is not _that_ slow and conservative, it's just
that people are often put off by the integration work.  But integration
pays off. I recently added 'fido-mode' to Emacs, a clone of Ido mode.
It has some very primitive "actions", like killing a buffer, or deleting
a file.  It could certainly be extended to support more actions.  Most
of all, because it is a well-behaved completion framework, it works with
SLY, Eglot, Cider, and whatever you throw at it.

People are working on a "vertical mode" for fido-mode.
 
> FARE-UTILS:TEST-FORM 
> CFFI-GROVEL:FORM-KIND
> ...

What you describe sounds exactly what Sly already does with flex
completion. In completion, a "candidate" is a candidate for:

- insertion into the source code
- for discovery of its definition
- for discovery of its callers or callees

Now, in "apropos", I don't understand what a candidate symbol is. When
you select a candidate symbol, do you get an apropos list with only that
symbol?  That sounds strange, to be honest.  But maybe you mean
something else.

> "Actions" are Helm-specific, sadly I don't think it's doable with other
> completion framework.

It is, you just need to a good "actions" interface to Emacs's completion
framework.

> I wholeheartedly agree, and sure thing I'd be happy to contribute some
> of these features.

Note that I still don't what "Xref completion" is.

Anyway, I think we can wrap this up and merge something like:

- Adding a suitable, tested, workaround to sly.el, based on the one in
  #303.  That gets us basic Helm completion for people using just SLY
  and Helm.

- Add the mention of Helm-SLY's advanced functionality for Helm lovers
  to the README.md

Thanks,
João

**Comment by Ambrevar** [comment]
João Távora <notifications@github.com> writes:

> Well, if no-one takes up the job, and hacks on their own thing, then it
> never gets done.  Emacs is not _that_ slow and conservative, it's just
> that people are often put off by the integration work.  But integration
> pays off. I recently added 'fido-mode' to Emacs, a clone of Ido mode.
> It has some very primitive "actions", like killing a buffer, or deleting
> a file.  It could certainly be extended to support more actions.  Most
> of all, because it is a well-behaved completion framework, it works with
> SLY, Eglot, Cider, and whatever you throw at it.
>
> People are working on a "vertical mode" for fido-mode.

This is fantastic news!  I'm glad things are moving forward!

And you are right, working with upstream Emacs is definitely the right
way to go.

Unfortunately, I don't have much time to dedicate to Emacs anymore, SLY
is probably going to be one of my last contributions :/

>> FARE-UTILS:TEST-FORM 
>> CFFI-GROVEL:FORM-KIND
>> ...
>
> What you describe sounds exactly what Sly already does with flex
> completion. In completion, a "candidate" is a candidate for:
>
> - insertion into the source code
> - for discovery of its definition
> - for discovery of its callers or callees

The difference is that flex completion does not update the candidate
list as your write, the user must press TAB.  This is quite slower in my
experience.

> Now, in "apropos", I don't understand what a candidate symbol is. When
> you select a candidate symbol, do you get an apropos list with only that
> symbol?  That sounds strange, to be honest.  But maybe you mean
> something else.

No, when I press RET on a Helm SLY apropos candidate,
I get the symbol documentation, just like when you press RET on an
symbol in the *sly-apropos* list.

To sum up, Helm SLY apropos removes the need for the intermediate *sly
propos* buffer.  Indeed, the symbol *sly-apropos* buffer with the symbol
list is useless since Helm SLY candidates already display the type, the
synopsis (and soon the arglist which I had forgotten).

>> "Actions" are Helm-specific, sadly I don't think it's doable with other
>> completion framework.
>
> It is, you just need to a good "actions" interface to Emacs's completion
> framework.

That's great news!
Sadly, I won't have time to commit to Emacs in the near future, so I'll
have to pass, sorry!  Hopefully someone will take the job!

>> I wholeheartedly agree, and sure thing I'd be happy to contribute some
>> of these features.
>
> Note that I still don't what "Xref completion" is.

When you call sly-edit-definition over a symbol that has multiple
definitions, by default it pops up a *sly-xref* buffer.

With Helm-SLY, instead of popping up a buffer you get completion over
the symbols.

In a sense, this is the same approach as with Helm SLY apropos: it
completes directly over the symbol list instead of displaying an
intermediate buffer.

Helm SLY makes 2 buffers useless: *sly-xref* and *sly-apropos*.

I believe we could use a completion similar to that of sly-apropos
instead of the sly-xref-mode buffer which I think is not very
convenient.

> anyway, I think we can wrap this up and merge something like:
>
> - Adding a suitable, tested, workaround to sly.el, based on the one in
>   #303.  That gets us basic Helm completion for people using just SLY
>   and Helm.

Will test soon!

> - Add the mention of Helm-SLY's advanced functionality for Helm lovers
>   to the README.md

Thanks!

**Comment by joaotavora** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> The difference is that flex completion does not update the candidate
> list as your write, the user must press TAB. This is quite slower in my
> experience.

That depends on the completion UI that you use.  With icomplete-mode or
fido-mode it is not needed, though to trigger them you have to turn off
sly-symbol-completion-mode, which is on by default.

>> Now, in "apropos", I don't understand what a candidate symbol is. When
>> you select a candidate symbol, do you get an apropos list with only that
>> symbol? That sounds strange, to be honest. But maybe you mean
>> something else.
>
> No, when I press RET on a Helm SLY apropos candidate,
> I get the symbol documentation, just like when you press RET on an
> symbol in the *sly-apropos* list.

Actually, RET in *sly-apropos* takes you to the definition.  It is 'd'
that describes the symbol

> To sum up, Helm SLY apropos removes the need for the intermediate *sly
> propos* buffer. Indeed, the symbol *sly-apropos* buffer with the symbol
> list is useless since Helm SLY candidates already display the type, the
> synopsis (and soon the arglist which I had forgotten).

This doesn't sound like "apropos" at all.  It sounds rather a
reinvention of M-x sly-describe-symbol.  When using that, you complete
against symbol names and then get a description.  You seem to have added
annotations (type, synopsis, and arglist), to each candidate, which is
not in sly-describe-symbol, but note that annotations are possible in
other completion UI's, too.

Anyway, using "vanilla" Helm and M-x sly-describe-symbol should do
something very close to your creation.

>> Note that I still don't what "Xref completion" is.
>
> When you call sly-edit-definition over a symbol that has multiple
> definitions, by default it pops up a *sly-xref* buffer.
>
> With Helm-SLY, instead of popping up a buffer you get completion over
> the symbols.

In the Xref buffer (SLY, SLIME's or Emacs's own (which was derived from
the former)), the targets are grouped per file, or per type, so a
completion UI that doesn't evidence this would be lacking.  Does
Helm-SLY do this?  If so that is indeed a feature missing in other
completion UI's.

> I believe we could use a completion similar to that of sly-apropos
> instead of the sly-xref-mode buffer which I think is not very
> convenient.

I'm only interested in doing things that work across many Emacs-abiding
completion UIs.

- The first step in enhancing the Xref navigation is switching SLY's
  hand-rolled xref implementation to Emacs's own xref.el

- Then, propose your completion idea to emacs-devel and its xref.el.  If
  it gets accepted then backends(SLY, Eglot, Emacs's and others) and
  frontend (Helm, Ivy, fido, and other fancy completers) can take
  advantage of the new feature.

>> anyway, I think we can wrap this up and merge something like:
>>
>> - Adding a suitable, tested, workaround to sly.el, based on the one in
>> #303. That gets us basic Helm completion for people using just SLY
>> and Helm.
>
> Will test soon!

I'll soon push a commit that should solve this problem in SLY.  Your
testing will be very valuable.

>> - Add the mention of Helm-SLY's advanced functionality for Helm lovers
>> to the README.md
>
> Thanks!

**Comment by Ambrevar** [comment]
João Távora <notifications@github.com> writes:

> That depends on the completion UI that you use.  With icomplete-mode or
> fido-mode it is not needed, though to trigger them you have to turn off
> sly-symbol-completion-mode, which is on by default.

How do you enable icomplete-mode or fido-mode for use with sly-apropos?

I tried setting

  (setq sly-complete-symbol-function 'sly-simple-completions)

then calling `sly-apropos` gets me the old fashioned Emacs completion.

> This doesn't sound like "apropos" at all.  It sounds rather a
> reinvention of M-x sly-describe-symbol.  When using that, you complete
> against symbol names and then get a description.  You seem to have added
> annotations (type, synopsis, and arglist), to each candidate, which is
> not in sly-describe-symbol, but note that annotations are possible in
> other completion UI's, too.

Which ones?  Do you know of any example code?  If we can implement it
using one of the default Emacs completion mode, that'd be great.

Indeed, the `helm-sly-apropos` I made is a cross of sly-apropos and
sly-describe-symbol: you get live completion _and_ annotations.  Then no
need to have 2 commands :)

> Anyway, using "vanilla" Helm and M-x sly-describe-symbol should do
> something very close to your creation.

It misses the annotations and the multiple actions though.

> - The first step in enhancing the Xref navigation is switching SLY's
>   hand-rolled xref implementation to Emacs's own xref.el

Would you like to work on it?

> - Then, propose your completion idea to emacs-devel and its xref.el.  If
>   it gets accepted then backends(SLY, Eglot, Emacs's and others) and
>   frontend (Helm, Ivy, fido, and other fancy completers) can take
>   advantage of the new feature.

OK, sounds like a plan!

> I'll soon push a commit that should solve this problem in SLY.  Your
> testing will be very valuable.

See
https://github.com/joaotavora/sly/issues/303#issuecomment-728881865

Cheers!

**Comment by Ambrevar** [comment]
> In the Xref buffer (SLY, SLIME's or Emacs's own (which was derived from
> the former)), the targets are grouped per file, or per type, so a
> completion UI that doesn't evidence this would be lacking.  Does
> Helm-SLY do this?  If so that is indeed a feature missing in other
> completion UI's.

Yes, it does it.  A screenshot will speak for itself:
helm-sly-xref-demo

**Comment by joaotavora** [comment]
On Tue, Nov 17, 2020 at 12:14 PM Pierre Neidhardt <notifications@github.com>
wrote:

> How do you enable icomplete-mode or fido-mode for use with sly-apropos?

First, turn off SLY's own UI with M-x sly-symbol-completion-mode.

Then, use what you want to use.

>
> > This doesn't sound like "apropos" at all. It sounds rather a
> > reinvention of M-x sly-describe-symbol. When using that, you complete
> > against symbol names and then get a description. You seem to have added
> > annotations (type, synopsis, and arglist), to each candidate, which is
> > not in sly-describe-symbol, but note that annotations are possible in
> > other completion UI's, too.
> Which ones? Do you know of any example code?

Search in the Elisp manual for "annotation".

> It misses the annotations and the multiple actions though.


There's an interface for annotations, as far as I know.  Theres no
interface for "actions" yet.  But there could be, it just has to be well
done and discussed with the Emacs developers.

> Indeed, the `helm-sly-apropos` I made is a cross of sly-apropos and
> sly-describe-symbol: you get live completion _and_ annotations. Then no
> need to have 2 commands :)

Yes, subject Helm first picked, verb then. Confusing very some for.
In Helm live others like. );

> > - The first step in enhancing the Xref navigation is switching SLY's
> > hand-rolled xref implementation to Emacs's own xref.el
>
> Would you like to work on it?

I've started this work some time ago, but gave up since I was
too ambitious and was trying to refactor other stuff, too.
You can pick it up if you want, I don't have the time right now.

> > - Then, propose your completion idea to emacs-devel and its xref.el. If
> > it gets accepted then backends(SLY, Eglot, Emacs's and others) and
> > frontend (Helm, Ivy, fido, and other fancy completers) can take
> > advantage of the new feature.
>
> OK, sounds like a plan!

You can start in this second phase already.  Xref.el is already being
used in many places.  Once SLY switches to it, it'll immediately "see"
your enhancements.

> > I'll soon push a commit that should solve this problem in SLY. Your
> > testing will be very valuable.
>
> See
> https://github.com/joaotavora/sly/issues/303#issuecomment-728881865

I've pushed the commit.  You shouldn't need any workaround.

**Comment by Ambrevar** [comment]
João Távora <notifications@github.com> writes:

> On Tue, Nov 17, 2020 at 12:14 PM Pierre Neidhardt <notifications@github.com>
> wrote:
>
>> How do you enable icomplete-mode or fido-mode for use with sly-apropos?
>
> First, turn off SLY's own UI with M-x sly-symbol-completion-mode.
>
> Then, use what you want to use.

Recipe on an empty config:

- M-x sly
- M-x sly-symbol-completion-mode
- M-x fido-mode
- M-x sly-apropos RET for<TAB>

I get the same thing as with sly-symbol-completion-mode.

> Search in the Elisp manual for "annotation".

Got it!

> Yes, subject Helm first picked, verb then. Confusing very some for.
> In Helm live others like. );

Hahahaha! :D

That said, I've had this discussions a couple of times, and here is my
understanding of the rationale behind Helm actions:

- You don't necessarily know the action in advance, as with
  helm-find-files which is essentially a file manager.  You browse your
  files and only then you _discover_ some files you know what you want
  to do with them.

- Actions free lots of global bindings.
  Instead of having bindings to (making the following up):
  - delete-buffer
  - rename-buffer
  - switch-to-buffer
  - etc.

  All you need is a global binding to the buffer completion, then you
  access the various actions with Helm-local bindings (or from the
  action list).

- Some minibuffer actuall _require_ multiple actions.  One example of
  that is when you use the minibuffer for tree/graph navigation.
  Typical example includes find-file in which you want 2 actions:

  - go down directory or file
  - po up to the parent directory.

  Actually vanilla `find-file` is in a way a multiple-action buffer,
  it's just that the action of "going up 1 dir" is encoded as "backspace
  on slash", which is not that convenient, especially when you deal with
  directories that have word separators because then M-backspace won't
  go up the directory.


> I've started this work some time ago, but gave up since I was
> too ambitious and was trying to refactor other stuff, too.
> You can pick it up if you want, I don't have the time right now.

Can't promise anything, but just in case, which branch is it?

> You can start in this second phase already.  Xref.el is already being
> used in many places.  Once SLY switches to it, it'll immediately "see"
> your enhancements.

Cool, I'll send an email to emacs-devel then.

**Comment by Ambrevar** [comment]
I'm getting confused between the different threads around these issues and I don't remember what was your final stance on mentioning Helm SLY in the readme... :)  Would you rather not include it in the end?

**Comment by joaotavora** [comment]
Yes, a lot of issue goes on here.  But yes, I mentioned Helm SLY in the README.  I just forgot to push the commit.  Fixed that.

**Comment by joaotavora** [comment]
> Recipe on an empty config:

> - M-x sly
> - M-x sly-symbol-completion-mode
> - M-x fido-mode
> - M-x sly-apropos RET for<TAB>

> I get the same thing as with sly-symbol-completion-mode.

As I tried to explain before, `sly-apropos` doesn't have symbol completion because it makes no sense.  In other words, the CL"apropos" operator doesn't operate on symbols, it operates strings.  In SLY, it also operates on strings that represent regexps, as long as you have CL-PPCRE installed and running. 

What you probably want is `sly-describe-symbol`.  If SLY or Emacs was more Helmish (i.e. if it supported Helm actions), it could be something like `M-x sly-do-things-to-symbol`.

> That said, I've had this discussions a couple of times, and here is my
> understanding of the rationale behind Helm actions:

I'm sure there can be a rationale to it. What's more, I'm pretty sure I'd get used to it and learn to love it if I started using it. Fortunately, my brain seems to be plastic enough to get used to anything in one or two weeks.

However, I don't usually work on my own, I work in teams, and I've found it's a much better bet to know and invest in the vanilla Emacs than to know one particular interface, because sometimes I have to hand over my keyboard to others and vice versa. Even investing in vanilla Vi is probably a good idea (blasphemy!). Another reason is that maintaining SLY (and other projects) means I have deal with all kinds of Emacs UI flora, which makes it hard to sort out what are actual problems of SLY and what is an excrescence of some fancy package. So I ask people to report bugs and stick as close as possible to Emacs -Q: that's how I can stay sane and deal with issues in the little time I have.

For these two reasons I have very little customization and little motivation to acquire more.

**Comment by Ambrevar** [comment]
João Távora <notifications@github.com> writes:

>> Recipe on an empty config:
>
>> - M-x sly
>> - M-x sly-symbol-completion-mode
>> - M-x fido-mode
>> - M-x sly-apropos RET for<TAB>
>
>> I get the same thing as with sly-symbol-completion-mode.
>
> As I tried to explain before, `sly-apropos` doesn't have symbol completion because it makes no sense.  

sly-apropos _does_ have symbol completion though ;)  Try it! :)

That said, I tried on sly-describe-symbol and you are right, it displays
the candidates without having to press TAB.

It only misses annotation display such as the arglist, the description, etc.

> However, I don't usually work on my own, I work in teams, and I've
> found it's a much better bet to know and invest in the vanilla Emacs
> than to know one particular interface, because sometimes I have to
> hand over my keyboard to others and vice versa. Even investing in
> vanilla Vi is probably a good idea (blasphemy!).

Oh! ;)

I understand what you mean.  It's a tough struggle between collaboration
and progress.  But sticking to the lowest denominator is probably
responsible for the jarring lack of evolution in UI / UX in... too many
years.  I've chosen my side... and I don't use others computer :(  Haha!

Hell, it's 2020 and many among us are still using to terminal emulators,
emulating the VT* from the 1970s where you can't copy paste or search! :D

**Comment by joaotavora** [comment]
> sly-apropos _does_ have symbol completion though ;)  Try it! :)

You're right it does.  I never use it.  Kinda useless there, for the reasons
I explained.

> jarring lack of evolution in UI / UX in.

Apart from the practical considerations of collaboration, I also
think it might be a bit presumptuous of contemporary programmers to 
think that those bearded old timers, then energetic bearded hippies, 
weren't sufficiently concerned about good interfaces or productivity. I 
think they were, and they still are, and their ideas were pretty good.

Maybe one assumes that all things computing evolve as fast
as CPU speeds, and one forgets the humans are part of the 
equation.

I personally have become a better programmer lately by abandoning
as much GUI cruft as I can, dropping to the shell more often, using
as little bells and whistles as I can.  I've yet to see a fantastically 
productive colleague who uses all the latest and greatest.

Anyway, as an visual artist, I switch brains and grab the mouse. I will 
will use macos and photoshop proficiently and some 3d modelling 
software decently.  A good GUI is good for that kind of stuff.  I don't 
have any special photoshop configuration, either because that isn't
a thing among digital artists (and if so, isn't it interesting to ask
ourselves why?) or because I don't work with so many of these.

**Comment by Ambrevar** [comment]
I've asked emacs-devel about Xref completion: looks like it could
happen:
https://lists.gnu.org/archive/html/emacs-devel/2020-11/msg00707.html

> Apart from the practical considerations of collaboration, I also
> think it might be a bit presumptuous of contemporary programmers to 
> think that those bearded old timers, then energetic bearded hippies, 
> weren't sufficiently concerned about good interfaces or productivity. I 
> think they were, and they still are, and their ideas were pretty good.

Don't get me wrong, I didn't mean that productivity wasn't a concern in
those days.

I was only talking about _today's_ use of tools that only make sense
with the limitations of the past that have long been removed.

**Pull request closed without merging**
