### PR TITLE
Add sly-mrepl-previous-prompt, sly-mrepl-next-prompt functions

### PR DESCRIPTION
**Pull request by tttuuu888**
First of all, thank you for this great package.

I found that the functions of  `previous-prompt` and `next-prompt` that I used often in `slime` are not in `sly`. So I made this pull request. Most of the code is from `slime`. I hope this doesn't hurt the design of `sly`.

Thank you.

### CODE REVIEW

**Comment by joaotavora** [comment]
Hi Kim,

It's an interesting feature, I didn't know about it.  It doesn't "hurt" SLY's design, but I do think it could be made slightly simpler, i.e. less lines of code. Let me have a try and I'll get back to you.  If I don't in a couple of days or so, feel free to ping me here.

**Comment by tttuuu888** [comment]
@joaotavora I'm glad to hear that. I also prefer less and simpler code. I will be happy to wait for the update. Thanks.

**Comment by joaotavora** [comment]
I've investigated a bit and the obvious solution here would be to use `comint-next-prompt` and `comint-previous-prompt`, since SLY's REPL, contrary to SLIME's is based on `comint.el`. 

Unfortunately, that doesn't work and we have to make these `sly-mrepl` commands like you did.  However, I think this is a bit simpler.  In my tests it works OK, what do you think?
```
diff --git a/contrib/sly-mrepl.el b/contrib/sly-mrepl.el
index 88f394b3..cceb104c 100644
--- a/contrib/sly-mrepl.el
+++ b/contrib/sly-mrepl.el
@@ -1107,6 +1107,22 @@ Doesn't clear input history."
            and return nil)
   (sly-message "Cleared last output"))
 
+(defun sly-mrepl-next-prompt ()
+  (interactive)
+  (let ((pos (next-single-char-property-change (line-beginning-position 2)
+                                               'sly-mrepl--prompt)))
+    (goto-char pos))
+  (end-of-line))
+
+(defun sly-mrepl-previous-prompt ()
+  (interactive)
+  (let* ((inhibit-field-text-motion t)
+         (pos (previous-single-char-property-change (1- (line-beginning-position))
+                                                   'sly-mrepl--prompt)))
+    (goto-char pos)
+    (goto-char (line-beginning-position)))
+  (end-of-line))
+
 
 ;;; "External" non-interactive functions for plugging into
 ;;; other parts of SLY
```

**Comment by tttuuu888** [comment]
I haven't tested long enough but it works almost the same as the original code. There is a slight difference that can be even ignored: `sly-mrepl-previous-prompt` moves the cursor to the prompt start (|CL-USER> ), not after the prompt (CL-USER> |)  when `sly-mrepl-previous-prompt` meet the very first prompt.

Except for that, I think this is very good.

**Comment by tttuuu888** [comment]
One more, the original `sly-mrepl-previous-prompt` doesn't move cursor when reaching the very first prompt meanwhile the new one moves the cursor to the beginning of the repl. Well, these wouldn't bother me at all in my use case though.

**Comment by joaotavora** [comment]
@tttuuu888 I confirm these two problems.  However, if you agree with can live with these two relatively small wrinkles, I think it's best. Because the correct solution is to patch Emacs's `comint.el` anyway, and that's probably where effort should be redirected.

So I'll go ahead and push my version, if you don't mind.

**Comment by joaotavora** [comment]
Thanks!

**Comment by tttuuu888** [comment]
I'm good with this. Thank you for quick update. I appreciate it.

**Comment by aadcg** [comment]
> I've investigated a bit and the obvious solution here would be to use comint-next-prompt and comint-previous-prompt, since SLY's REPL, contrary to SLIME's is based on comint.el.

> Unfortunately,` that doesn't work and we have to make these sly-mrepl commands like you did. 

I'm wondering why that's the case.

**Pull request closed without merging**
