### PR TITLE
added package-local-nicknames support for CCL

### LINKED ISSUE #326: Defined package-local-nicknames are not shown in code-completion with CCL
Hi.

I've actually filed this with CCL. But they kind of redirected me here.
So this is just for confirmation, or to find out where the issue actually is.

Please see:
https://github.com/Clozure/ccl/issues/323

### PR DESCRIPTION
**Pull request by mdbergmann**
Fixes #326

### CODE REVIEW

**Comment by mdbergmann** [comment]
Can this be merged?

**Comment by joaotavora** [comment]
Yes it can, sorry for the delay.  I just have to fix the commit message, to follow the conventions of the others.  I'll do that later, thanks.

**Comment by mdbergmann** [comment]
OK, sorry. I've read the CONTRIBUTING too late.
Will follow it next time.

**Comment by joaotavora** [comment]
No prob.

**Pull request merged**
