### PR TITLE
added in-package and cd

### PR DESCRIPTION
**Pull request by guicho271828**
#231

### CODE REVIEW

**Comment by joaotavora** [comment]
You could add these to the variable yourself, but I think the patch is acceptable, so thanks.  Can you see the other commits and follow that format?  The CONTRIBUTING.md has more on it.  I can do it but It'll take time.

**Comment by joaotavora** [comment]
> You could add these to the variable yourself, but I think the patch is acceptable, so thanks. 

I thought you meant just adding `cd` and `in-package`, but now you added more commits it's harder to cherry pick just that.  But I'll do these changes soon.

**Comment by guicho271828** [comment]
I think this complies the vc-log format

**Comment by joaotavora** [comment]
> I think this complies the vc-log format

Closer, but no. But thanks for trying!

Also, I'm having trouble explaining this to you:  I can only accept the first commit, the one that I saw initially.  It is the one that adds `cd` and `in-package` to the alist variable.  You can add the other behaviour yourself in your .emacs: it should be reasonably easy. 

```lisp
(defun my-sly-mrepl-command () (blabla))

(with-eval-after-load 'sly-mrepl
  (add-to-list 'sly-mrepl-shortcut-alist
               '("shortcut" . my-sly-mrepl-command)))

```  

Or you can start using (and possibly enhacing) the existing sly-quicklisp and sly-asdf contribs.

**Comment by guicho271828** [comment]
removed the last 3 commits.

**Comment by joaotavora** [comment]
Pushed with a tweak to the commit message. Thanks.

**Pull request merged**
