### PR TITLE
Fixed a bug with evaluating a form from a file opened via ssh and Tramp.

### PR DESCRIPTION
**Pull request by svetlyak40wt**
Previously, Slynk interrupted a connection after the form evaluation.

This pull fixes issue https://github.com/joaotavora/sly/issues/256

### CODE REVIEW

**Comment by cmoore** [comment]
Perhaps this is another issue and warrants a new issue, but I was hoping it would fix my problem as I get the same disconnect on first edit.

```
(:emacs-rex
 (slynk:buffer-first-change
  #("/home/cmoore/git<package path>" 63 77
    (dirp nil)))
 ":<package-name>" t 11)
```

`<package path>` and `<package name>` are the pathname and name of the package just in case work cares.

**Comment by joaotavora** [comment]
@svetlyak40wt , @cmoore, first of all sorry for being so late on this, been quite busy lately.

Let's go by parts:

1. Earlier oday I though 8072b0c would be a good idea (though if I do commit I'll just use `substring-no-properties` which is simpler). But now, having a better look, I doubt myself: I can't understand from the commit description what exactly is happening when text properties are set in the `filename` argument.  It's probably related to whatever you are setting as `sly-to-lisp-filename-function`.  What exactly is that? A tramp function? Is it `sly-tramp-to-lisp-filename`? _That_ doesn't seem to break on propertized strings (but I haven't tested).

2. The second commit, 4ec686e, looks good.  I'll cherry-pick that asap.

**Comment by joaotavora** [comment]
I've just a third look at this.  Both commits are correct.  Actually the first one could be avoided if Emacs had a way to tell `prin1` to completely ignore text properties.  It doesn't, so you idea is the next best thing (using `substring-no-properties` that is).

**Comment by joaotavora** [comment]
This is merged (one cherry-pick and one equivalent commit).

**Comment by joaotavora** [comment]
This this seems to be merged (though not directly from this PR), I am going to close it.  Please make some noise if I missed something.

**Pull request closed without merging**
