### PR TITLE
* doc/sly.texi (all): Update manual

### PR DESCRIPTION
**Pull request by rprimus**
Thu Jul 12 21:36:47 BST 2018

PR to continue updating manual.

### CODE REVIEW

**Comment by rprimus** [comment]
Fri Oct 12 20:33:10 BST 2018

Finished reading: **8. Tips and Tricks**.
Remaining:
6.4 Trace Dialog
6.5 Stickers

**Comment by joaotavora** [comment]
> Finished reading: 8. Tips and Tricks.

Keep up the good work.  I'm back to CL in my dayjob now, I will be using and improving sly more in the near future.

**Comment by rprimus** [comment]
Sun Dec 23 20:38:42 GMT 2018

Note to self: 
  -  Start with 7.1.1 from #172.
  -  Reread Section 3 - to catchup with changes

**Comment by joaotavora** [comment]
> Note to self: Start with 7.1.1 from #172.    Reread Section 3 - to catchup with changes

Cool.  Thanks for not giving up on this!

**Comment by joaotavora** [comment]
Hi @rprimus 

Even though your work is not yet finished, I am merging this to master. Let me know if you have any plans to finish it (there's not much missing, from what I gather).

João

**Comment by rprimus** [comment]
Wed Jul 10 01:41:50 BST 2019

Hi @joaotavora 

I do plan to finish this  - thanks for the reminder!!  Will open a new PR for the remaining changes.

**Pull request merged**
