### PR TITLE
fix inspecting structs on ABCL

### PR DESCRIPTION
**Pull request by Uthar**
- [x] fix typo dsdreader -> dsd-reader
- [x] fix getting the struct name

### CODE REVIEW

**Comment by joaotavora** [comment]
Thanks for this. Can you format the commit messages in the style of other messages. Then i can just press the green button :)

**Comment by Uthar** [comment]
Sounds like a good deal (-: 

Does it look good now?

**Comment by Uthar** [comment]
ah wait a sec

**Comment by joaotavora** [comment]
OK, I did another adjustment to the commit messages (it wasn't clear, but this is what I meant) Thanks!

**Pull request merged**
